### ISSUE TITLE
updates for ifcViewer methods addAxes and addGrid

### ISSUE THREAD

**Issue by legacy5813** [helenkwok/wiv-hello-world-vite#1]
inside IfcContainer.tsx lines 12 and 13:

ifcViewer.addAxes() depreciated and update into ifcViewer.axes.setAxes()

ifcViewer.addGrid() depreciated and update into ifcViewer.grid.setGrid()

they added properties axes and grid you can access separate methods for each like above.

this ifc js with vite works a lot smoother good work!

**Comment by helenkwok** [comment]
Thank you for your comments. It is updated accordingly.
